services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - kong
    volumes:
      - ./data:/app/backend/data
    environment:
      OLLAMA_BASE_URL: http://ollama:11434

networks:
  kong:
    external: true
