test -d env || mkdir env; cd env;

export APOLLO_CONFIG_DB_USERNAME=${APOLLO_CONFIG_DB_USERNAME:-$(test -f APOLLO_CONFIG_DB_USERNAME && cat APOLLO_CONFIG_DB_USERNAME || echo apollo | tee APOLLO_CONFIG_DB_USERNAME)}
export APOLLO_CONFIG_DB_PASSWORD=${APOLLO_CONFIG_DB_PASSWORD:-$(test -f APOLLO_CONFIG_DB_PASSWORD && cat APOLLO_CONFIG_DB_PASSWORD || uuidgen | tee APOLLO_CONFIG_DB_PASSWORD)}
export APOLLO_PORTAL_DB_USERNAME=${APOLLO_PORTAL_DB_USERNAME:-$(test -f APOLLO_PORTAL_DB_USERNAME && cat APOLLO_PORTAL_DB_USERNAME || echo apollo | tee APOLLO_PORTAL_DB_USERNAME)}
export APOLLO_PORTAL_DB_PASSWORD=${APOLLO_PORTAL_DB_PASSWORD:-$(test -f APOLLO_PORTAL_DB_PASSWORD && cat APOLLO_PORTAL_DB_PASSWORD || uuidgen | tee APOLLO_PORTAL_DB_PASSWORD)}
