services:
  qbittorrent:
    image: "t0twn/qbittorrent"
    user: "1001:1001"
    command: --profile=/etc/
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - QBT_NO_SPLASH=1
    volumes:
      - ./etc/:/etc/qBittorrent/:rw
      - ./data/:/data/qBittorrent/:rw
    ports:
      - "56660:56660/tcp"
      - "56660:56660/udp"
    networks:
      - kong
    restart: always

networks:
  kong:
    external: true
