services:
  haproxy:
    image: "haproxy:latest"
    networks:
      - kong-net
    restart: always
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy:ro
    ports:
      - "::1:80:80/tcp"
      - "::1:443:443/tcp"
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
