services:
  openlist:
    image: 'openlistteam/openlist:latest'
    container_name: openlist
    user: '99:99'
    volumes:
      - './data/:/opt/openlist/data'
    ports:
      - '127.0.0.1:5244:5244'
    networks:
      - kong
    environment:
      - UMASK=022
    restart: unless-stopped

networks:
  kong:
    external: true
